/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData bars_sort = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars_progress = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_shopping = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_shopping_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData books = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_cheese = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_fries = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_soda = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_soda_solid = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day_solid = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cars = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_shopping = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_shopping_fast = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_tree_map = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_tree_map_solid = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left_solid = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_solid = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_left_solid = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_right_solid = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData church = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_check = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_chevron_down = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_chevron_left = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_chevron_right = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_chevron_up = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_question = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_hail_mixed = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData display = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_wide = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landmark = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lips = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_dot = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_keyhole = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData masks_theater = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper_solid = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_1 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popcorn = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popcorn_solid = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale_balanced = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seal_question = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_simple = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_solid = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
 
  static const IconData bag_shopping = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballot = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
